name: TheBrewingProject
main: dev.jsinco.brewery.bukkit.TheBrewingProject
description: 'Help me.'
authors: [Jsinco, Mitality, Nadwey]
version: '${version}'
api-version: '1.20'
softdepend:
  - Oraxen
  - ItemsAdder
